### ISSUE TITLE
Useless attributes value reassignments

### ISSUE THREAD

**Issue by Metastasis** [kriskate/dota-backend#1]
First you replace AttributePrimary and AttackCapabilities with readable values
https://github.com/kriskate/dota-backend/blob/a2cff6665155bcf07c1acc311776175d88dd77ea/data/hero_utils.js#L37
And then you make forEach which in turn erases previous values
https://github.com/kriskate/dota-backend/blob/a2cff6665155bcf07c1acc311776175d88dd77ea/data/hero_utils.js#L39

Why do you need this last line?

**Comment by kriskate** [comment]
That's true, I'm actually using the original dota game values in the end product. I've pushed the change to the branch ```git-pusher```, as I've detached from master a bit

Also, there are lots of improvements to be made, a lot of refactoring to be done in order to keep a minimal RAM footprint.
